In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [5]:
data = pd.read_csv("C:\\Python\\kNN\\data.csv")

In [6]:
print (data.describe())

       HouseHold Number  Income($000)  Lot size(000s sqft)
count         24.000000     24.000000            24.000000
mean          12.500000     68.437500            18.950000
std            7.071068     19.793144             2.428275
min            1.000000     33.000000            14.000000
25%            6.750000     52.350000            17.500000
50%           12.500000     64.800000            19.000000
75%           18.250000     83.100000            20.800000
max           24.000000    110.100000            23.600000


In [7]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()

In [9]:
dataVal  =data.values

In [11]:
X = dataVal[:,1:3]
y = dataVal[:,3]

In [12]:
y

array(['Non Owner', 'Owner', 'Owner', 'Owner', 'Owner', 'Owner', 'Owner',
       'Owner', 'Owner', 'Owner', 'Owner', 'Owner', 'Non Owner',
       'Non Owner', 'Non Owner', 'Non Owner', 'Non Owner', 'Non Owner',
       'Non Owner', 'Non Owner', 'Non Owner', 'Non Owner', 'Non Owner',
       'Owner'], dtype=object)

In [13]:
labelEncoder  =labelEncoder.fit(y)
y_encoded = labelEncoder.transform(y)

In [14]:
y_encoded

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1], dtype=int64)

In [15]:
X

array([[47.4, 16.4],
       [85.5, 16.8],
       [64.8, 21.6],
       [61.5, 20.8],
       [87.0, 23.6],
       [60.0, 18.4],
       [108.0, 17.6],
       [82.8, 22.4],
       [69.0, 20.0],
       [93.0, 20.8],
       [51.0, 22.0],
       [81.0, 20.0],
       [75.0, 19.6],
       [52.8, 20.8],
       [64.8, 17.2],
       [43.2, 20.4],
       [84.0, 17.6],
       [49.2, 17.6],
       [59.4, 16.0],
       [66.0, 18.4],
       [33.0, 18.8],
       [51.0, 14.0],
       [63.0, 14.8],
       [110.1, 19.2]], dtype=object)

In [16]:
X_Train,X_Text,Y_Train,Y_Test = train_test_split(X,y_encoded,test_size=0.3,random_state=3)

In [17]:
# knn classifier needs 3 argument
#1 - number of kneighbors
#2- metric  -minkowski
#3 - power which in turn represents the distance metric used e.g ecludian, manhattan etc
model = KNeighborsClassifier(n_neighbors=3,metric="minkowski",p=2)


In [18]:
#train the model
model.fit(X_Train,Y_Train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [29]:
XPred = model.predict(X_Train)


In [32]:
confusion_matrix(Y_Train,XPred)


array([[4, 2],
       [1, 9]], dtype=int64)

In [33]:
accuracy_score(Y_Train,XPred)

0.8125

In [34]:
YPred = model.predict(X_Text)

In [35]:
confusion_matrix(Y_Test,YPred)


array([[3, 3],
       [0, 2]], dtype=int64)

In [36]:
accuracy_score(Y_Test,YPred)

0.625

In [37]:
for n in [1,3,5]:
    model = KNeighborsClassifier(n_neighbors=n,metric="minkowski",p=2)
    model.fit(X_Train,Y_Train)
    XPred = model.predict(X_Train)
    print (accuracy_score(Y_Train,XPred))
    YPred = model.predict(X_Text)
    print (accuracy_score(Y_Test,YPred))
    

    

1.0
0.75
0.8125
0.625
0.8125
0.5
